### ISSUE TITLE
SImple stats page

### ISSUE THREAD

**Issue by hagiali** [gamershost/GamersHost-Bot#3]
Can we have a simple stats page? Or with forum integration like the deleted tables from DB?
Now, the expired banned players aren't removed from bans table.

**Comment by Grief-Code** [comment]
The forum integration you are looking for is here:
https://github.com/Grief-Code/IPS-Stats
But this is only done for the IPS Forum Software.

Maybe in the future there will be a small statspage. But currently it is not planned.

**Comment by hagiali** [comment]
so we need the IPS forum. but we need the missing tables for foru side.
